# Generated by Django 5.2.7 on 2025-10-30 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField()),
                ('philhealth_number', models.CharField(blank=True, max_length=20, null=True)),
                ('not_enrolled_philhealth', models.BooleanField(default=False)),
                ('philsys_number', models.CharField(blank=True, max_length=20, null=True)),
                ('no_philsys_number', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_first_2_letters', models.CharField(max_length=2)),
                ('father_first_2_letters', models.CharField(max_length=2)),
                ('birth_order', models.PositiveIntegerField()),
                ('birth_date', models.DateField()),
                ('age', models.PositiveIntegerField()),
                ('age_in_months', models.PositiveIntegerField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('gender_identity', models.CharField(blank=True, choices=[('Man', 'Man'), ('Woman', 'Woman'), ('Other', 'Other')], max_length=10, null=True)),
                ('gender_other_specify', models.CharField(blank=True, max_length=100, null=True)),
                ('current_residence_city', models.CharField(max_length=100)),
                ('current_residence_province', models.CharField(max_length=100)),
                ('permanent_residence_city', models.CharField(max_length=100)),
                ('permanent_residence_province', models.CharField(max_length=100)),
                ('place_of_birth_city', models.CharField(max_length=100)),
                ('place_of_birth_province', models.CharField(max_length=100)),
                ('is_filipino', models.BooleanField(default=True)),
                ('other_nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('civil_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Separated', 'Separated'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced')], max_length=10)),
                ('living_with_partner', models.BooleanField(default=False)),
                ('number_of_children', models.PositiveIntegerField(blank=True, null=True)),
                ('currently_pregnant', models.BooleanField(default=False)),
                ('contact_number', models.CharField(max_length=11)),
                ('email_address', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
