# Generated by Django 5.2.7 on 2025-11-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinformation',
            name='current_occupation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='patientinformation',
            name='currently_in_school',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='patientinformation',
            name='currently_working',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='patientinformation',
            name='highest_education_attainment',
            field=models.CharField(choices=[('No grade completed', 'No grade completed'), ('Pre-school', 'Pre-school'), ('Elementary', 'Elementary'), ('Highschool', 'Highschool'), ('Vocational', 'Vocational'), ('College', 'College'), ('Post-Graduate', 'Post-Graduate'), ('N/A', 'N/A')], default='N/A', max_length=30),
        ),
        migrations.AddField(
            model_name='patientinformation',
            name='last_country_worked',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='patientinformation',
            name='last_port_of_exit',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='patientinformation',
            name='previous_occupation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='patientinformation',
            name='work_abroad_location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='patientinformation',
            name='work_type',
            field=models.CharField(choices=[('Ship', 'On Ship'), ('Land', 'On Land'), ('N/A', 'N/A')], default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='patientinformation',
            name='worked_abroad_past_5_years',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='patientinformation',
            name='worked_overseas',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'N/A')], default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='patientinformation',
            name='year_return_from_abroad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
