# Generated by Django 5.2.7 on 2025-11-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_patientinformation_current_occupation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HivTesting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_mother_hiv', models.CharField(choices=[('Do not know', 'Do not know'), ('No', 'No'), ('Yes', 'Yes')], default='Do not know', max_length=20)),
                ('sex_partner_count', models.PositiveIntegerField(blank=True, null=True)),
                ('sexual_activity', models.BooleanField(default=False)),
                ('most_recent_anal_or_neovaginal_sex', models.CharField(blank=True, max_length=7, null=True)),
                ('most_recent_condomless_sex', models.CharField(blank=True, max_length=7, null=True)),
                ('sex_with_male', models.BooleanField(default=False)),
                ('sex_with_female', models.BooleanField(default=False)),
                ('oral', models.BooleanField(default=False)),
                ('anal_inserter', models.BooleanField(default=False)),
                ('anal_receiver', models.BooleanField(default=False)),
                ('vaginal_inserter', models.BooleanField(default=False)),
                ('vaginal_receiver', models.BooleanField(default=False)),
                ('condom_use', models.CharField(blank=True, choices=[('Always', 'Always'), ('Sometimes', 'Sometimes'), ('Never', 'Never')], max_length=10, null=True)),
                ('paid_for_sex', models.BooleanField(default=False)),
                ('date_paid_for_sex', models.CharField(blank=True, max_length=7, null=True)),
                ('received_payment_for_sex', models.BooleanField(default=False)),
                ('date_received_payment', models.CharField(blank=True, max_length=7, null=True)),
                ('sex_under_influence', models.BooleanField(default=False)),
                ('date_sex_under_influence', models.CharField(blank=True, max_length=7, null=True)),
                ('shared_needles', models.BooleanField(default=False)),
                ('date_shared_needles', models.CharField(blank=True, max_length=7, null=True)),
                ('received_transfusion', models.BooleanField(default=False)),
                ('date_received_transfusion', models.CharField(blank=True, max_length=7, null=True)),
                ('occupational_exposure', models.BooleanField(default=False)),
                ('date_occupational_exposure', models.CharField(blank=True, max_length=7, null=True)),
                ('possible_exposure', models.BooleanField(default=False)),
                ('recommended_by_physician', models.BooleanField(default=False)),
                ('referred_by_peer_educator', models.BooleanField(default=False)),
                ('employment_overseas', models.BooleanField(default=False)),
                ('employment_local', models.BooleanField(default=False)),
                ('insurance_requirement', models.BooleanField(default=False)),
                ('received_text_invite', models.BooleanField(default=False)),
                ('other_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('tested_before', models.BooleanField(default=False)),
                ('date_of_last_test', models.CharField(blank=True, max_length=7, null=True)),
                ('test_facility', models.CharField(blank=True, max_length=255, null=True)),
                ('result', models.CharField(blank=True, choices=[('Reactive', 'Reactive'), ('Non-reactive', 'Non-reactive'), ('Indeterminate', 'Indeterminate'), ('Was not able to get result', 'Was not able to get result')], max_length=26, null=True)),
                ('city_municipality', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
