# Generated by Django 5.2.7 on 2025-11-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_hivtesting_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hivtesting',
            old_name='sex_partner_count',
            new_name='sex_partner_count_female',
        ),
        migrations.AddField(
            model_name='hivtesting',
            name='sex_partner_count_male',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
