# Generated by Django 5.2.7 on 2025-11-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_sex_partner_count_hivtesting_sex_partner_count_female_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hivtesting',
            old_name='most_recent_anal_or_neovaginal_sex',
            new_name='most_recent_anal_or_neovaginal_sex_female',
        ),
        migrations.RenameField(
            model_name='hivtesting',
            old_name='most_recent_condomless_sex',
            new_name='most_recent_anal_or_neovaginal_sex_male',
        ),
        migrations.RenameField(
            model_name='hivtesting',
            old_name='sexual_activity',
            new_name='sexual_activity_female',
        ),
        migrations.AddField(
            model_name='hivtesting',
            name='most_recent_condomless_sex_female',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='hivtesting',
            name='most_recent_condomless_sex_male',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='hivtesting',
            name='sexual_activity_male',
            field=models.BooleanField(default=False),
        ),
    ]
