# Generated by Django 5.2.7 on 2025-11-18 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_most_recent_anal_or_neovaginal_sex_hivtesting_most_recent_anal_or_neovaginal_sex_female_and_m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientinformation',
            name='test_date',
        ),
    ]
