# pdf_generator.py
import os
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
from django.conf import settings

def generate_patient_pdf(patient, hiv_testing):
    """
    Generates a single PDF with patient info on page 1
    and HIV testing info on page 2.
    """
    pdf_path = os.path.join(settings.MEDIA_ROOT, "pdfs", f"combined_{patient.id}.pdf")
    os.makedirs(os.path.dirname(pdf_path), exist_ok=True)
    width, height = letter
    c = canvas.Canvas(pdf_path, pagesize=letter)

    # --- PAGE 1: PATIENT INFORMATION ---
    template_image = os.path.join(settings.MEDIA_ROOT, "forms", "blank.jpg")
    if os.path.exists(template_image):
        form_bg = ImageReader(template_image)
        c.drawImage(form_bg, 0, 0, width=width, height=height)

    c.setFont("Helvetica", 10)
    c.drawString(100, 680, f"NAME: {patient.last_name}, {patient.first_name} {patient.middle_name or ''} {patient.suffix or ''}")
    c.drawString(100, 660, f"PHILHEALTH: {patient.philhealth_number or 'N/A'}")
    c.drawString(100, 640, f"PHILSYS: {patient.philsys_number or 'N/A'}")
    c.drawString(100, 620, f"SEX: {patient.sex}")
    c.drawString(100, 600, f"AGE: {patient.age} ({patient.age_in_months or 'N/A'} months)")
    c.drawString(100, 580, f"GENDER IDENTITY: {patient.gender_identity or 'N/A'}")
    c.drawString(100, 560, f"CIVIL STATUS: {patient.civil_status}")
    c.drawString(100, 540, f"CURRENT RESIDENCE: {patient.current_residence_city}, {patient.current_residence_province}")
    c.drawString(100, 520, f"PERMANENT RESIDENCE: {patient.permanent_residence_city}, {patient.permanent_residence_province}")
    c.drawString(100, 500, f"PLACE OF BIRTH: {patient.place_of_birth_city}, {patient.place_of_birth_province}")
    c.drawString(100, 480, f"NATIONALITY: {'Filipino' if patient.is_filipino else patient.other_nationality or 'N/A'}")
    c.drawString(100, 460, f"LIVING WITH PARTNER: {'Yes' if patient.living_with_partner else 'No'}")
    c.drawString(100, 440, f"CHILDREN: {patient.number_of_children or 0}")
    c.drawString(100, 420, f"PREGNANT: {'Yes' if patient.currently_pregnant else 'No'}")

    # Footer for page 1
    c.setFont("Helvetica-Oblique", 8)
    c.drawString(50, 100, "Generated by Django ReportLab - Patient Information Form")

    # Finish page 1
    c.showPage()

    # --- PAGE 2: HIV TESTING INFORMATION ---
    # c.setFont("Helvetica", 10)
    # c.drawString(100, 700, f"BIRTH MOTHER HIV STATUS: {hiv_testing.birth_mother_hiv}")
    # c.drawString(100, 680, f"SEX WITH MALE: {'Yes' if hiv_testing.sex_with_male else 'No'}")
    # c.drawString(100, 660, f"SEX WITH FEMALE: {'Yes' if hiv_testing.sex_with_female else 'No'}")
    # c.drawString(100, 640, f"SEX PARTNERS MALE: {hiv_testing.sex_partner_count_male or 'N/A'}")
    # c.drawString(100, 620, f"SEX PARTNERS FEMALE: {hiv_testing.sex_partner_count_female or 'N/A'}")
    # c.drawString(100, 600, f"SEXUAL ACTIVITY MALE: {'Yes' if hiv_testing.sexual_activity_male else 'No'}")
    # c.drawString(100, 580, f"SEXUAL ACTIVITY FEMALE: {'Yes' if hiv_testing.sexual_activity_female else 'No'}")
    # c.drawString(100, 560, f"ORAL SEX: {'Yes' if hiv_testing.oral else 'No'}")
    # c.drawString(100, 540, f"ANAL INSERTER: {'Yes' if hiv_testing.anal_inserter else 'No'}")
    # c.drawString(100, 520, f"ANAL RECEIVER: {'Yes' if hiv_testing.anal_receiver else 'No'}")
    # c.drawString(100, 500, f"VAGINAL INSERTER: {'Yes' if hiv_testing.vaginal_inserter else 'No'}")
    # c.drawString(100, 480, f"VAGINAL RECEIVER: {'Yes' if hiv_testing.vaginal_receiver else 'No'}")
    # c.drawString(100, 460, f"CONDOM USE: {hiv_testing.condom_use or 'N/A'}")
    # c.drawString(100, 440, f"TESTED BEFORE: {'Yes' if hiv_testing.tested_before else 'No'}")
    # c.drawString(100, 420, f"LAST TEST DATE: {hiv_testing.date_of_last_test or 'N/A'}")
    # c.drawString(100, 400, f"RESULT: {hiv_testing.result or 'N/A'}")
    # c.drawString(100, 380, f"TEST FACILITY: {hiv_testing.test_facility or 'N/A'}")
    # c.drawString(100, 360, f"CITY/MUNICIPALITY: {hiv_testing.city_municipality or 'N/A'}")

    # Footer for page 2
    c.setFont("Helvetica-Oblique", 8)
    c.drawString(50, 100, "Generated by Django ReportLab - HIV Testing Form")

    # Save PDF
    c.save()
    return pdf_path
